### ISSUE TITLE
Create DRT Flag list data dictionary

### ISSUE THREAD

**Issue by abrahamagedewICPI** [ICPI/DAQ#13]
Need to create a data dictionary for the flag list table.

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/Data%20Access%20and%20Quality%20(DAQ)/Data%20Review%20Tool%20(DRT)/Working%20documents/Code%20for%20DRT%20(SQL%2C%20Code%20Builder%2C%20VBA)/DRT_FlagList_All.xlsx

**Comment by abeagedew** [comment]
Flag list has been updated
