### ISSUE TITLE
Adding approval level to DRT dataset?

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#15]
We received a request from the systems team to add a feature to DRT to make security trimming testing easier:

"In today's stand-up, we were discussing things to help test and it came up that it would be important to show the Approval Levels in DRT to the user. After a bit more discussion, we all realized that it is already there in SiteByIM. 

We all felt that this would be a great thing to add to DRT so that it matches SiteByIM (shows Approval Level). Can we do this for the upcoming production DRT release."

**Comment by abrahamagedewICPI** [comment]
I think we should include in the back-end raw data and possibly create a pivot/slicer. It might be a useful information if users are looking at in-process data (not at the Global level) and provides a good contextual information on the approval status for the desired validation rule.
