### ISSUE TITLE
Create MSD Training/Testing Dataset with FY18Q2 changes

### ISSUE THREAD

**Issue by abrahamagedewICPI** [ICPI/DAQ#19]
EPIC For Training Dataset

**Comment by abrahamagedewICPI** [comment]
[Q2 Mockup_20180418.xlsx](https://github.com/ICPI/DAQ/files/1924777/Q2.Mockup_20180418.xlsx)
@kschlenker, a more abridged mock-up dataset

**Comment by shapaklyak** [comment]
not sure if you're planning to compare previous dataset structure to proposed changes, but i was working on this to try to prep for the OVC dashboard updates for q2.

![image](https://user-images.githubusercontent.com/5234106/38959137-7348e89c-432d-11e8-87cf-e757b6829a9c.png)
