### ISSUE TITLE
DAQ Draft membership list

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#2]
DAQ members should review the roles & responsibilities and provide their information on the membership list tab of this document. 

The current draft SOW and workplan activities are included as reference in this document but updates, edits, etc to those tabs will be tracked in other tickets

**Comment by Couper-T** [comment]
[DAQ.Workplan_Membership_List_draft_2018.03.27.xlsx](https://github.com/ICPI/DAQ/files/1852830/DAQ.Workplan_Membership_List_draft_2018.03.27.xlsx)

I updated my row.

**Comment by abrahamagedewICPI** [comment]
[DAQ.Workplan_Membership_List_draft_2018.03.27.xlsx](https://github.com/ICPI/DAQ/files/1852839/DAQ.Workplan_Membership_List_draft_2018.03.27.xlsx)
Updated LOE

**Comment by shazadahmed10** [comment]
[DAQ Workplan_Membership_List_draft_2018 03 27_SA.xlsx](https://github.com/ICPI/DAQ/files/1852944/DAQ.Workplan_Membership_List_draft_2018.03.27_SA.xlsx)

Updated with Shazad's info

**Comment by abrahamagedewICPI** [comment]
[DAQ.Workplan_Membership_List_draft_2018.03.27.xlsx](https://github.com/ICPI/DAQ/files/1853009/DAQ.Workplan_Membership_List_draft_2018.03.27.xlsx)
Updated with @imujawar and @wvp3  membership info

**Comment by abrahamagedewICPI** [comment]
Please use the latest version if updating membership info

**Comment by shapaklyak** [comment]
[DAQ.Workplan_Membership_List_draft_2018.03.28v2.xlsx](https://github.com/ICPI/DAQ/files/1856424/DAQ.Workplan_Membership_List_draft_2018.03.28v2.xlsx)

updated with my membership info

**Comment by abrahamagedewICPI** [comment]
[DAQ.Workplan_Membership_List_draft_2018.03.28.xlsx](https://github.com/ICPI/DAQ/files/1856431/DAQ.Workplan_Membership_List_draft_2018.03.28.xlsx)

LATEST VERSION

**Comment by achafetz** [comment]
updated.
[DAQ.Workplan_Membership_List_draft_2018.03.28.xlsx](https://github.com/ICPI/DAQ/files/1856811/DAQ.Workplan_Membership_List_draft_2018.03.28.xlsx)

**Comment by abrahamagedewICPI** [comment]
@achafetz, do you know which worklanes you are interested in participating or contributing to?

**Comment by achafetz** [comment]
done!
[DAQ.Workplan_Membership_List_draft_2018.03.28.xlsx](https://github.com/ICPI/DAQ/files/1857539/DAQ.Workplan_Membership_List_draft_2018.03.28.xlsx)

**Comment by abrahamagedewICPI** [comment]
[DAQ.Workplan_Membership_List_draft_2018.03.28.xlsx](https://github.com/ICPI/DAQ/files/1857996/DAQ.Workplan_Membership_List_draft_2018.03.28.xlsx)

LATEST VERSION
