### ISSUE TITLE
SIMS Structured Dataset Training Materials/Webinar

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#20]
@mehtasp & Audrey will take the lead on developing/adapting training materials for the SIMS Structured Datasets (SSDs). This will include a live webinar presentation that does a shallow dive on the datasets and any supplemental materials needed - which could include supplemental slidedeck, pre-recorded video, training dataset, etc. as needed.

**Comment by kschlenker** [comment]
@mehtasp Discussed this @ the DAQ leads meeting and, upon further discussion, we thought it would be best to keep the shallow-dive DAQ/PRIME webinar focused on MER for the sake of cohesion. But we should still proceed to create training materials & think about when (June? late May?) it would be most appropriate to hold a standalone SIMS SD webinar.

**Comment by mehtasp** [comment]
That's fine. I can work with Audrey on this. I'll probably be out most of June, but end of May and mid-July would work. I can bring this up with Audrey when she's here next week.

**Comment by shapaklyak** [comment]
hi all, is there a SIMS training dataset? thanks!

**Comment by abeagedew** [comment]
@shapaklyak, the SIMS training dataset is posted [here ](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Data%20Store%2FSIMS%2FTraining&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC00C3CC873FA325DD44884DEFC36053A859&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D)on SP. I believe Audrey is working on updating the training materials.
