### ISSUE TITLE
MSD & Site x IM Extract Training Materials/Webinar

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#22]
@aliyahwakil @abrahamagedewICPI @kschlenker @anu87 will adapt/update training materials for the Site x IM Genie Extracts & MER Structured Datasets (MSDs). This will include a live webinar presentation that does a shallow dive on the extracts & datasets and any supplemental materials needed - which could include supplemental slidedeck, pre-recorded video, training dataset, etc. as needed.

**Comment by kkale25** [comment]
@ICPI/daq - is there a timeline around this?

**Comment by abeagedew** [comment]
Materials posted here : https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Data%20Store%2FMER%2FTraining&FolderCTID=0x0120004DAC66286D0B8344836739DA850ACB95&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D
