### ISSUE TITLE
Review VMMC Followup calculated indicator

### ISSUE THREAD

**Issue by abrahamagedewICPI** [ICPI/DAQ#30]
VMMC team has requested for the VMMC Followup calculated indicator to be revised.  Request submitted by Britteny Baack(@bbaack )

![image](https://user-images.githubusercontent.com/18145327/39712835-81a87a6e-51f2-11e8-8ddb-de6afaa15b07.png)

**Comment by bowdenj** [comment]
Thank you Abe! If it is expected that this will be included in Q2, is there a plan to notify Derek/Stephanie so they can add it to the disagg code map or DDE?

**Comment by abrahamagedewICPI** [comment]
Derek is aware
