### ISSUE TITLE
Demo/training pivot tables with new MSD

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#34]
As discussed during the DAQ meeting, we will develop sample pivot tables using the PSNU x IM Training Dataset (Ticket #33) for the following:

- [x] HTS_TST (@abrahamagedewICPI )

- [x] PMTCT (@achafetz)

- [x] VMMC (@mehtasp) - done and posted [here](https://github.com/ICPI/DAQ/tree/master/Training)

- [x] TX (@imujawar) 

- [x] OVC_SERV (@shapaklyak - Are you able to work on this?)

The idea is to show how to properly construct a simple table with your indicator(s), demo how to create tables using key disaggregations (potentially with the associated calculated indicators), and how to look across time at that indicator (FY17 & FY18 only). 

Some of the HTS indicators will be demo'd in #22 MSD webinar with OGAC. Others will serve as supplemental training/job aid materials that people can reference. 

**Deadline: COB Thursday 5/24**

**Comment by mehtasp** [comment]
Created VMMC sample pivots using the ICPI_MER_Structured_Dataset_PSNU_IM_FY17-18_20180515_v1_1_Uganda. (The training PSNUxIM files I found on Sharepoint only went up to FY17Q4). Posted them in the sharepoint location above.

**Comment by achafetz** [comment]
here's an [updated masked training dataset](https://github.com/ICPI/TrainingDataset/raw/master/Output/ICPI_MER_Structured_TRAINING_Dataset_PSNU_IM_FY17-18_20180515_v1_1.txt) for Q2. Code and other info can be found on the [ICPI/TrainingDataset](https://github.com/ICPI/TrainingDataset) repo

**Comment by abrahamagedewICPI** [comment]
Awesome Aaron!

**Comment by achafetz** [comment]
Here are the PMTCT pivots. Checking them off the list
[PMTCT_Training_Pivots.xlsx](https://github.com/ICPI/DAQ/files/2039664/PMTCT_Training_Pivots.xlsx)

**Comment by shapaklyak** [comment]
@achafetz code wasn't working for me to read the training dataset into R. i installed readr package

![image](https://user-images.githubusercontent.com/5234106/40553113-b6c7118a-600f-11e8-94ac-3f185d11c2ae.png)

**Comment by shapaklyak** [comment]
@achafetz figured it out... the code needs to be updated to the correct url 
`df <- readr::read_tsv("https://github.com/ICPI/TrainingDataset/raw/master/Output/ICPI_MER_Structured_TRAINING_Dataset_PSNU_IM_FY17-18_20180515_v1_1.txt")`

**Comment by abrahamagedewICPI** [comment]
Training materials can be posted [here ](https://github.com/ICPI/DAQ/tree/master/Training)in Github

**Comment by shapaklyak** [comment]
@erinschelar  please review 
[OVC_Training_Pivots.xlsx](https://github.com/ICPI/DAQ/files/2040402/OVC_Training_Pivots.xlsx)

**Comment by achafetz** [comment]
thanks @shapaklyak. I needed to update the README after I added the new file. This is resolved now.

perfect opportunity for a pull request in the future :)

**Comment by kschlenker** [comment]
@achafetz @mehtasp @abrahamagedewICPI @shapaklyak @imujawar 

We spoke with Kristin R today regarding the previously scheduled OGAC/DAQ webinar. The webinar will not be taking place Thursday but we'd like to try to get some pre-recorded training videos online by Friday. 

Abe & I thought it might be nice to have a few mini recordings on creating videos for specific subject areas. Is anyone available to record a short adobe connect video walking users through the just set of pivot tables you did for you've already created? It could be a chance to mention any caveats you think are important about that particular technical area when using the MSDs. Please respond with any availability or feedback about this idea

(Also - @hessionra has kindly offered to assist if we need help with Adobe connect recordings)

**Comment by abrahamagedewICPI** [comment]
@mehtasp @achafetz @imujawar @shapaklyak  , let us know if you are able to coordinate with @hessionra to create the recordings.

**Comment by abrahamagedewICPI** [comment]
Next steps:
- Finalize and compile Excel workbooks by 6/4
- Video recording for HTS_TST  6/4

**Comment by hessionra** [comment]
Recording with @kschlenker tomorrow 6/1.

**Comment by imujawar** [comment]
Posting TX pivots. [TX_Training_Pivots.xlsx](https://github.com/ICPI/DAQ/files/2078341/TX_Training_Pivots.xlsx)

**Comment by shazadahmed10** [comment]
HTS pivots cheat sheet link  (too big to post on GitHub):

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/HIV-TB%20Diagnosis/Resources/HTS_CheatSheet%20Fy18Q2.xlsx

**Comment by shapaklyak** [comment]
will all of these be compiled in the Training folder for DAQ on github and/or sharepoint? some prevention folks are interested. fyi @kimisatoPC @erinschelar
