### ISSUE TITLE
Training Dataset update

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/DAQ#38]
The Training dataset is a bit sparse, is it possible to create one that uses a larger/medium sized OU? This would be helpful for preparing materials for the Tableau training and other cluster training materials.

**Comment by achafetz** [comment]
the Trainign Dataset extracts 25 districts at random from the MSD and bins them into 3 OUs. It's 25 because (a) it keep it to a small file and (b) I couldn't come up with any more GoT names. 

If you want to think up more names, pull request away
https://github.com/ICPI/TrainingDataset/blob/master/Input/got_geo.csv

**Comment by achafetz** [comment]
and it's limited to 45 partners as well 

https://github.com/ICPI/TrainingDataset/blob/master/Input/got_primepartner.csv

**Comment by shapaklyak** [comment]
can you use [Land of Oz](https://en.wikipedia.org/wiki/Land_of_Oz#Geography)? Also, the issue isn't more geographic areas, it's the type of data pulled in for indicators appears incomplete. For example, there are FY18 results but no targets for OVC transferred. @abrahamagedewICPI  - is it more complete for HTS?

**Comment by abrahamagedewICPI** [comment]
@shapaklyak , HTS is looks alright to me in the training dataset

**Comment by kschlenker** [comment]
@shapaklyak & @achafetz I'm happy to add more places & partner names after my AL. Agreed that we don't want a dataset so large that it's unusable but we can afford to make it a bit larger to make it more likely that we have fuller representation of some of the indicators that might be limited to a few of partners and/or PSNUs (e.g., OVC & KP)

**Comment by shapaklyak** [comment]
@kschlenker @achafetz are either of you or anyone able to make the training dataset more  comprehensive this week? it'd be great to use as part of developing training materials this week.

**Comment by abeagedew** [comment]
Hi @shapaklyak, I started working on the comprehensive workbook, planning on finalizing it tomorrow. I will post it in the training folder here on GH and SP.

**Comment by shapaklyak** [comment]
thank you @abrahamagedewICPI ! this will be very helpful to create materials for the Tableau training!
