### ISSUE TITLE
Draft workplan presentation for leads

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#4]
Current draft presentation of workplan for leads posted:

**Comment by abrahamagedewICPI** [comment]
Updated version.

[DAQ Presentations to Leads 20180329.pptx](https://github.com/ICPI/DAQ/files/1861258/DAQ.Presentations.to.Leads.20180329.pptx)

**Comment by kschlenker** [comment]
Reformatted membership slide and added a reference (hidden) slide about the DAQ roles since they differ slightly from what other clusters have used.

**Comment by abrahamagedewICPI** [comment]
[DAQ Presentations to Leads 20180329.pptx](https://github.com/ICPI/DAQ/files/1861772/DAQ.Presentations.to.Leads.20180329.pptx)

Update based on @kkale25 feedback to include collaborations with other teams in the Coordination Cluster.
