### ISSUE TITLE
Q2 known issues

### ISSUE THREAD

**Issue by abrahamagedewICPI** [ICPI/DAQ#40]
- [x] -Add Sex to VMMC and PMTCT testing modalities as implied sex
- [x] -Account for KP_PREV (keypop), TX_NEW (keypop), PrEP_new(keypop), GEND_GBV(ViolenceType), TX_PVLS(Indication), HTS_TST(keypop), TX_RET(PregnantOrBreastfeeding) in other disaggs variable- currently in cat combo options
- [ ] -Standardize modalites and also need to removed for MER 1 service delivery points
- [x] -TX_TB implied Total Numerator and Denom - Use HIVStatus as Total Numerator and Denominator
- [x] -Primary age disagg for coarse aggregation for OVC_SERV and PMTCT_HEI_POS
- [x] -Standardize Unknown Age and Unknown Sex
- [x] -Remove all NA and NULL values
- [x] -Decrease value decimal points to 2 decimals
- [ ] -Retroactively apply OVC_SERV TransferExit disaggregate from ProgramStatus
- [ ] -VMMC_CIRC_FollowUp calculated indicator for FY15 and FY16

**Comment by kschlenker** [comment]
@abrahamagedewICPI can you confirm which of these were (or were not) corrected for the Q2 clean release?

**Comment by kschlenker** [comment]
from @abrahamagedewICPI all fixes "except the VMMC_CIRC_FOLLOWUP are in the clean release"

**Comment by kimisatoPC** [comment]
@abrahamagedewICPI can you confirm that Rwanda will be added to the DREAMS dataset for cleaned Q2? Thank you!

**Comment by abeagedew** [comment]
@kimisatoPC , we will confirm the inclusion of Rwanda to the DREAMS dataset. It will be part of our testing. Thanks for bringing this up.

**Comment by achafetz** [comment]
"N/A" was removed from `Sex` and `resultStatus` and NULL from `modality` but were replaced with a space rather than left blank. where do we lodge our complaints?

![image](https://user-images.githubusercontent.com/8933069/42184330-28402042-7e13-11e8-9e55-0506e1e5e029.png)

![image](https://user-images.githubusercontent.com/8933069/42184365-464b5886-7e13-11e8-9a87-92e3ef592cde.png)

**Comment by bowdenj** [comment]
Hey @achafetz , thanks for asking. You can log tickets here: https://datim.zendesk.com/hc/en-us/requests/new?ticket_form_id=54655

For now, please select "Data Genie" in the dropdown menu. Hoping to get this label updated to include MSD. Thank you!

**Comment by bowdenj** [comment]
@achafetz - can you please also include in the ticket where you found it (OU specific PSNU x IM/Site x IM? OUxIM? Other?)

**Comment by achafetz** [comment]
Sure thing. And do you know if ICPI intentionally left off the file title or not?
`MER_Structured_Dataset_OU_IM_FY17-18_20180622_v2_1.txt` was formerly `ICPI_MER_Structured_Dataset_OU_IM_FY17-18_20180515_v1_1`. All these changes have implications on our code

**Comment by bowdenj** [comment]
@achafetz - Yes, we did have to adjust this branding now that it is a shared product. Apologies for the code change. It will look like this moving forward, so this should be a one-time change.

**Comment by achafetz** [comment]
Thanks!

**Comment by shapaklyak** [comment]
hi @achafetz @kschlenker ...it seems that the Exited w/o Graduation and Transferred disaggs (under Other Disagge) are duplicated in the dataset under "NA" and "TransferExit". I'll submit a ticket but wanted to let you know of this issue here.
