### ISSUE TITLE
Standardize MSD Training Pivots

### ISSUE THREAD

**Issue by abeagedew** [ICPI/DAQ#42]
Pick a format that can be adopted from the  different program area pivot tables and update the pivot examples using the chosen format.

https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Data%20Store%2FMER%2FTraining&FolderCTID=0x0120004DAC66286D0B8344836739DA850ACB95&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D

**Comment by kschlenker** [comment]
Given the new addition of TX_NET_NEW to the MSDs, is there anyone (@imujawar @aliyahwakil ???) who would be able to update our MSD TX Training Pivot Table workbook with some Net_New examples?

**Comment by aliyahwakil** [comment]
I can create some examples @kschlenker

**Comment by abeagedew** [comment]
Updated Training documents are posted [here](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Data%20Store%2FMER%2FTraining&FolderCTID=0x0120004DAC66286D0B8344836739DA850ACB95&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence).
