### ISSUE TITLE
Brainstorming new age band structure/display

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#46]
As discussed during today's DAQ meeting it would be good for us to brainstorm potential solutions related to how we would prefer to see the new _super fine_ (kidding) five year age bands for MER 2.3 displayed in the MSDs. I'm not sure how far along the systems team is in terms of thinking through options. But if we have proposals then we can see if they're receptive. 

Below I've sketched out one possible option that makes sense in my mind. Please provide feedback & alternatives! The example I have follows how data from a 42 year old that was reported at the lowest possible level of granularity (at the time) would be displayed in FY17-FY18Q1 (original MER 2.0); from FY18Q2-Q4 (introduction of fine age bands); and FY19 (the true 5 year age bands). 

This idea retains the current 4 column structure (though might require some renaming depending on the verbage that OGAC prefers...maybe something like AgeFineTrends to indicate that it isn't the actual 5 year age bands??). I haven't thought through too much how analytics that bring in MER 1.0 & incompatible age bands might play out though (but then again, I'm not sure how much people are actually trying to look at age disagg'd data prior to FY17). 

Comment away and please brainstorm other possible ways of handling the age bands in this thread!

![agebandproposal](https://user-images.githubusercontent.com/19845271/46975654-32747e80-d095-11e8-8a9e-80d006036279.jpg)

**Comment by achafetz** [comment]
This might a controversial thought, but... do we really need all these different age bands included? Having the <15/15+ is probably useful to have as well.

My hot take would be the folks who are using the MSD are the same people who can create a "mapping" themselves based on their needs if its necessary. This might make it easier for a new/less experiences user to have not as many columns to deal with and minimize the consternation as to what age column to use.

**Comment by achafetz** [comment]
Another unsolicited hot take is that I think it would be great to cut another column - `disaggregate`.  The only difference is with HTS_TST/HTS_TST_POS and I would argue anyone using `disaggregate` column doesn't know `standardizeddisaggregate` exists. It's exponentially much more complex to deal with disaggs based on the their normal disaggregate.

**Comment by kschlenker** [comment]
Deadline for soliciting feedback: Friday, Oct 26th. 

We'll have a final discussion at the DAQ meeting on the 28th before presenting our suggestions to PRIME Systems on the 29th

**Comment by imujawar** [comment]
My vote is for... **Getting rid of `isMCAD`**, but have the columns `AgeFine`, `AgeSemiFine`, and `AgeCoarse`, reflect the 'Most Complete' age for that age granularity level. `AgeAsEntered` would reflect the true age entered anyway. This will be more intuitive, and wouldn't require instructions on complex ways of filtering age data. With this system, all one has to do is pick the desired age grouping and it will be the most complete age for that level of granularity. Happy to provide an example next week before the brainstorming, but wanted to put this out there. 

Also, agree with Aaron about getting rid of `disaggregate` column.

**Comment by aliyahwakil** [comment]
If it's likely that people won't be looking at disagg'd data prior to FY17, can we get rid of AgeFine since, like Imran mentioned, AgeAsEntered will have the most complete and granular level? This could limit confusion and would cut down on the amount of different age bands to keep track of.

**Comment by imujawar** [comment]
> If it's likely that people won't be looking at disagg'd data prior to FY17, can we get rid of AgeFine since, like Imran mentioned, AgeAsEntered will have the most complete and granular level? This could limit confusion and would cut down on the amount of different age bands to keep track of.

Very much in support of reducing columns, especially columns for age bands, but I think we can't really get rid of `AgeFine`, since we may get even finer data going forward, and each coarser level of age granularity would capture the most complete level from the more finer age band below. Also, `AgeAsEntered` may contain a mishmash of data various levels of granularity.
