### ISSUE TITLE
Feedback wanted: MSD structure for TB & cervical cancer results

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#47]
We're soliciting feedback to give to the systems team about how results status for TB & cervical cancer should be handled in MSDs. Currently two formats are being debated and we want you to weigh in!

**Option 1:** Have a single OtherStatus column that contains both TB results and cervical cancer results 

Indicator | Disaggregate | categoryOptionComboName | HIV Status | OtherStatus
-- | -- | -- | -- | --
HTS_TST | Modality/Age/Sex/Result | 10-14, Female, Positive | Positive |  
TX_TB | TBScreen/NewExistingART/HIVStatus | Life-long ART, New, TB Screen - Negative, Positive | Positive | Negative
CXCA_SCREEN | Age/Sex/HIVStatus/ScreenResult/ScreenVisitType | 15-19, Female, Positive, Cervical Cancer Screened - First Time, Cervical Cancer - Negative | Positive | Negative

**Option 2:** use two separate columns for TB results and for cervical cancer results

Indicator | Disaggregate | categoryOptionComboName | HIV Status | TB Status | Cervical Cancer status
-- | -- | -- | -- | -- | --
HTS_TST | Modality/Age/Sex/Result | 10-14, Female, Positive | Positive |   |  
TX_TB | TBScreen/NewExistingART/HIVStatus | Life-long ART, New, TB Screen - Negative, Positive | Positive | Negative |  
CXCA_SCREEN | Age/Sex/HIVStatus/ScreenResult/ScreenVisitType | 15-19, Female, Positive, Cervical Cancer Screened - First Time, Cervical Cancer - Negative | Positive |   | Negative

The biggest question in my mind is: does it seem at all feasible that one day we might have an indicator that looks at the cross-section of TB results & cervical caner results? If not, then a single column would suffice. If such an indicator did eventually get created then we'd need two separate columns

reference: https://github.com/pepfar-datim/Data-Warehouse/issues/2943

**Comment by kschlenker** [comment]
Feedback from DAQ meeting:
Option 2 generally sounds fine with people (this seems to be what systems team was leaning towards already). DAQ strongly suggests renaming column headers with a consistent naming convention to make it user friendly:

- StatusHIV (or Status_HIV)
- StatusTB (or Status_TB)
- StatusCX (or Status_CX)

**Comment by abeagedew** [comment]
To be implemented for FY19Q1.
