### ISSUE TITLE
Update DRT Template

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#5]
DRT Excel template needs the following updates:

- [x] language on intro tab updated to reflect Q2 & planned fast-follow release to add Disagg Completeness Checks
- [x] anonymize  screenshots on intro tab
- [x]  update appendix with Q2 checks

Upload completed Excel template to OGAC's DataWarehouse repo & notify Jim

**Comment by abrahamagedewICPI** [comment]
@kschlenker, can the status be changed to 'Completed'?
