### ISSUE TITLE
DRT revision for FY19Q1

### ISSUE THREAD

**Issue by abeagedew** [ICPI/DAQ#51]
Following changes have been made to the DRT validation checks:

- [x] TB_ART_N greater than TB_STAT_POS_N
- [x] Is   TX_PVLS_D in current period greater than TX_CURR in current period?
- [x] PMTCT_ART   Already on ART is greater than PMTCT_STAT_POS Known Status
- [ ] PMTCT_HEI_POS_N   and PMTCT_EID_N are not both reported (not null and null).
- [x] PMTCT_HEI_POS_N   reported (not null) and PMTCT_EID_N not reported (null).
- [x] PMTCT_EID_N   reported (not null) and PMTCT_HEI_POS_N not reported (null).
- [x] Current   period results reported, but no previous period results reported for   PMTCT_HEI_POS
- [x] Previous   results reported, but no current results reported for PMTCT_HEI_POS
- [x] TX_CURR_N   and TX_PVLS_D are not both reported (not null and null).
- [x] TX_CURR_N   reported (not null) and TX_PVLS_D not reported (null)
- [x] TX_PVLS_D   reported (not null) and TX_CURR_N not reported (null)
- [ ] TX_CURR_N   and TX_TB_D results are not both reported (not null and null)
- [x] TX_CURR_N   reported (not null) and TX_TB_D not reported (null)
- [x] TX_TB_D   reported (not null) and TX_CURR_N not reported (null)
- [x] TX_TB_D   is greater than TX_TB_N
- [x] TX_TB_D   is greater than TX_TB_D POS
- [x] TX_TB_D   is greater than TX_TB_D NEG
- [x] TX_TB_D   NEG is greater than TX_TB_D POS
- [x] TX_TB_D   is greater than TX_TB_D Specimen Sent
- [x] TX_TB_D   is greater than TX_TB_D Positive Result Returned
- [x] TX_TB_D   is greater than TX_TB_D Diagnostic sent
- [ ] TX_TB_D:   targets reported (not null), but no results reported (null)
- [x] TB_PREV_D   is greater than TB_PREV N
- [x] TB_PREV_D:   targets reported (not null), but no results reported (null)
- [x] TB_PREV_N:   targets reported (not null), but no results reported (null)
- [x] TB_PREV_N   reported (not null) and TB_PREV_D not reported (null)
- [x] TB_PREV_N   not reported (null) and TB_PREV_D reported (not null)
- [ ] Site/IM has targets reported for HTS_Index   in this fiscal year
- [x] Site/IM has results reported for HTS_Index
- [ ] Site/IM has results and targets reported for   HTS_Index
- [ ] Targets reported, but no current period   results for HTS_Index
- [ ] current period results reported, but no   targets reported for HTS_Index
- [ ] previous period results reported, but no   current period results reported for HTS_Index
- [ ] current period results reported, but no   previous period results reported for HTS_Index
- [x] PrEp_New - Change from quarterly to Semi
- [x] TB_ART  - Change from semi to quarterly
- [x] TB_ART - remove Denominator check 
- [x] TB_STAT  - Change from semi to quarterly
- [x] TX_PVLS - Change from annual to quarterly  
- [x] TX_RET - deactivate 
- [x] Deactivate Disaggregate Checks - Auto-calc total num/denom - FlagList table update
- [ ] TX_PVLS:  TX_PVLS Total Denom greater than Lab_PTCQI/Viral Load-Testing Volume - Requires script change
- [x] Activate VMMC_CIRC Technique disagg completeness checks
- [x] PMTCT_ART   N is greater than PMTCT_STAT_POS (PMTCT_ART D)
- [x] PMTCT_EID_N   is greater than [PMTCT_STAT_POS + HTS_TST_POS (PostANC1)]  (PMTCT_EID Proxy D)

**Comment by jaliasd** [comment]
Hi Everyone, you can find the 'crosswalks' for Nigeria and Mozambique [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2fOGAC-HQ%2ficpi%2fShared%20Documents%2fClusters%2fData%20Access%20and%20Quality%20%28DAQ%29%2fData%20Review%20Tool%20%28DRT%29%2fWorking%20documents&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A)

The countries compared the checks that they were doing in-house with what's in the DRT
