### ISSUE TITLE
Addition of SNU2 to Site by MSD dataset

### ISSUE THREAD

**Issue by jb3436** [ICPI/DAQ#52]
_From @shazadahmed10 on February 11, 2019 15:34_

Requester: Leigh Tally
Request: To add SNU2 as a new column to the Q4 Site by MSD dataset for Rwanda. Follow up request to add the same column to the in-process Rwadna MSD as well.
Status: Completed for the Q4 MSD by Shazad. Used the DATIM org hierarchy dataset circulated by Josh. Took SNU2 and orgunituid from org hierarchy file and merged OrgUnitUID to the Site by IM MSD. Sent the updated MSD directly to Leigh.

Table where there is another level between PSNU and Community, posted by Pooja:
![snu2 table](https://user-images.githubusercontent.com/8259381/52574901-3f0ea680-2deb-11e9-91c4-e0c9479ceada.JPG)

Final Script & Product Posted here:
### https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FData%20Access%20and%20Quality%20%28DAQ%29%2FAd%20Hoc%20Requests&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence
--

_Copied from original issue: ICPI/ICPIutilities#48_

**Comment by jb3436** [comment]
_From @shazadahmed10 on February 11, 2019 15:48_

Update: Request for same addition, but to the in-process Rwanda dataset

**Comment by shazadahmed10** [comment]
Update: Leigh sent the "in-process"  Rwanda site data. Shazad then ran code to merge SNU2 to this dataset.
Shazad sent it back to Leigh in an email. 

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FData%20Access%20and%20Quality%20%28DAQ%29%2FAd%20Hoc%20Requests&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence

**Comment by shazadahmed10** [comment]
Update: Request from Leigh to add SNU2 to frozen 19Q1 Rwanda site MSD when it is released around  2/22/19

**Comment by shazadahmed10** [comment]
Update: Shazad added SNU2 to 2/19 Genie output for Rwanda. Leigh provided dataset to be modified.
Processed dataset sent directly to Leigh and placed here on SP:

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/Data%20Access%20and%20Quality%20(DAQ)/Ad%20Hoc%20Requests/Rwanda_SiteMSD_withSNU2_022019.zip
