### ISSUE TITLE
Genie Users Reports

### ISSUE THREAD

**Issue by jb3436** [ICPI/DAQ#56]
Genie Users
--

Since October 1, 2018  36 OUs have had their data extracted from the Genie App
For a total download of over 2800
This includes ICPI and SI advisors.

Genie User Report on SP
[DAQ >Data Review Tool](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FData%20Access%20and%20Quality%20%28DAQ%29%2FData%20Review%20Tool%20%28DRT%29&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

Save Analysis in Same Folder

Next Steps
--

- [x] Analyse User Report and develop a summary @nmcarloni @faithfawale 
    - Who is using the DRT?
    - Where, Which agency, which role?
- Develop an outline for a user group survey (DAQ) @nmcarloni 
    - What is useful in the DRT
    - What is redundant
    - What can be added to make it more useful
- Once survey has been vetted by group and PRIME, PRIME will contact users to distribute the survey

**Comment by jb3436** [comment]
This report has been updated by Stephanie 
@shazadahmed10 will upload new version in folder 
@shazadahmed10 and Stephanie will determine where this report should live in the future

**Comment by shazadahmed10** [comment]
Permanent folder moved to [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FData%20Access%20and%20Quality%20%28DAQ%29%2FGenie%20Users%20Report%20%28quarterly%29&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) in ICPI SP page


19Q2 report [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/Data%20Access%20and%20Quality%20(DAQ)/Genie%20Users%20Report%20(quarterly)/Genie.User.Report.Summary%2019Q2.xlsx)
