### ISSUE TITLE
Genie Testing FY19Q2

### ISSUE THREAD

**Issue by jb3436** [ICPI/DAQ#60]
Genie Testing
--

1. Navigate to Genie test URL:  dev.pdh.datim.org
    - Please log into DATIM like you normally would and navigate to the Genie app. 
    - Please let Stephanie know if you cannot log in.
 
2. Note depending on your internet connection (and if it is a hotspot or metered connection) the download size for many Site x IM and PSNU x IM could be quite large. 
    - Please plan to test from a location where the size will not cause an issue.
3.  Testing User Story:
    - The data fetch & download limit for Site x IM needs to be larger so that a whole OU can be downloaded at a time.
    - The Site x IM row limit in the Genie test environment has been increased to 9.5 million records
    - Please test both Site x IM  - Frozen report and Daily report to see if the size increase works on some of the larger OUs such as Tanzania, Kenya, Nigeria, South Africa, Ethiopia, etc

4. Please send your feedback to Stephanie and William  via Slack or Email
    - Please let us know what worked, what didn’t, any weird error messages and any suggestions. 
    - Mostly we are looking for suggestions related to this issue, but other suggestions can be taken and put into a ticket for future development

**Comment by shazadahmed10** [comment]
Update 3/25: All OUs have been made available through the frozen toggle in Dev Pano. 

**Testing of Semi-Long format**: 
   - Row limit in the genie increased to 9.5 million
   - Frozen and daily
   - Daily worked fine for all Ous - tested large Ous
   - Frozen ones had errors - the row limit error said it was too high, and the other was round filters, though there were none
   - Frozen still needs to be worked 
   - Need to check in status

Update on 4/8 DAQ call:
All OUs have been made available through the frozen toggle in Dev Pano.

**Comment by shazadahmed10** [comment]
Next Step: Ask for volunteers with Dev Genie access to test the Genie MSD frozen outputs
