### ISSUE TITLE
MER Cheat Sheet Updates for Q2 Initial 

### ISSUE THREAD

**Issue by shazadahmed10** [ICPI/DAQ#68]

**Comment by shazadahmed10** [comment]
Cheat Sheets to be Updated to support User Guide
--

### Status
- [ ] HTS @shazadahmed10 
- [ ] PMTCT @KatieOC 
- [ ] Treatment @imujawar to connect with @MicSherlock 
- [ ] TB @cnichols3h 
- [ ] OVC @shapaklyak and @erinschelar , @faithfawale draft of OVC pivot courtesy of @faithfawale stored [here ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FOVC%2FMSD%20Cheatsheets%2DMay%202019&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by shazadahmed10** [comment]
Previously existing cheat sheets/training pivots:

[Training Pivots_TX_OVC_PMTCT_VMMC_v1_0_20181211.xlsx](https://github.com/ICPI/DAQ/files/3167569/Training.Pivots_TX_OVC_PMTCT_VMMC_v1_0_20181211.xlsx)

**Comment by shazadahmed10** [comment]
Plan: 
 - figure out which data to use in updated training pivot (mock or in-process)
    - if mock, how to update mock dataset with current data
 - check up on timeline for POCs for updating
 - whether to merge back into one file

**Comment by shazadahmed10** [comment]
Update from 5/23 meeting: 

Shazad to reach out to Faith on OVC progress. Shazad to revive this GH issue to get everyone implicated on board. 

Try to get done by end of June.

Issues: which data to use (mock or real), expand the indicators?

**Comment by shazadahmed10** [comment]
Update from 6/18 DAQ meeting:

@aliyahwakil & @anu87 will lead efforts on updating the pre-existing file (see above)
@kimisatoPC  & @erinschelar will create a new file for AGYW_PREV and update the OVC pivots

Kickoff meeting on Thursday 6/20 at 2:30 in N. America being led by Shazad. 

Requirements:
 - HTS, PMTCT, TX, TB, OVC, AGYW_PREV training pivots
 - update pre-existing pivots with new structured Q2 data
 - consistent formatting 
 - when updated, get blessing of program POCs, if possible 
 - Finalize by 7/19. 
 - use Q2 initial MSD? last time we used mock data

**Comment by shazadahmed10** [comment]
Meeting Notes

- Use one OU, one that has reported on all disaggs for all implicated indicators (Botswana)
- wait until clean MSDs are released
- HTS will be stand alone file again
- @shazadahmed10 to send HTS file

**Comment by aliyahwakil** [comment]
Training pivots status:
- [ ] HTS - in progress
- [x] PMTCT - completed
- [x] TX - completed
- [ ] TB - in progress
- [x] OVC - in final review
- [x] AGYW_PREV - final version posted to DREAMS folder

**Comment by jleehurst** [comment]
@aliyahwakil @erinschelar 
The completed OVC Cheat Sheets Pivot has been uploaded in the designated cheat sheet folder on Pepfar.net. We can mark as complete.

**Comment by shazadahmed10** [comment]
Thanks all for updating!  New [link](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Data%20Store%2FMER%2FTraining%2FMER%20Cheat%20Sheets%20%28Training%20Pivots%29&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC00C3CC873FA325DD44884DEFC36053A859&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)
