### ISSUE TITLE
Nigeria SNU prioritization levels missing

### ISSUE THREAD

**Issue by anu87** [ICPI/DAQ#72]
Scale-up level is missing in SNU prioritization data for Nigeria.

**Comment by WilliamShiflett** [comment]
@anu87 , Thank you for flagging this. Can you specify the MSD in which the SNU prioritization data is missing for Nigeria?

**Comment by WilliamShiflett** [comment]
@oharasl FYI

**Comment by anu87** [comment]
@WilliamShiflett This is the case in Site level data in PAW and Site x IM MSD.

**Comment by oharasl** [comment]
@anu87 can you please email us or log a ticket here: https://datim.zendesk.com/hc/en-us/requests/new
For issues in the PRIME systems, we need to track it officially and the ICPI repo is not ideal for ticket resolution (public site and it's outside of our domain).

**Comment by WilliamShiflett** [comment]
@anu87 , would you please create a ticket for this issue via the help desk? This helps us organize and triage incoming tickets and assign them to different repositories. 

For this issue, we will need to investigate why we do not have prioritization for Nigeria.

**Comment by anu87** [comment]
@WilliamShiflett @oharasl Submitted a ticket on Zendesk.

**Comment by anu87** [comment]
@WilliamShiflett @oharasl @wvp3 I checked with someone from Nigeria team - for FY19 they don't have scale-up, only sustained level - thus there are no data in Scale-up SNU prioritization level.
