### ISSUE TITLE
PLHIV Data Available for Analytics- NAT SUBNAT

### ISSUE THREAD

**Issue by shazadahmed10** [ICPI/DAQ#73]
Jasmine: I would also like to add a request around getting the PLHIV data from the datapacks into the PDH and pushed out so they are available in MSD, Genie, and PAWS.  Does anyone know if there is a plan for this already and if so what is the timeline? 

Stephanie: We don’t yet have a plan, but thank you for the request—we can create a ticket and try to understand the priority with our other activities.

**Comment by jb3436** [comment]
@shazadahmed10  through the import process, those data should be available in DATIM. 
@oharasl I suggest setting up a meeting with Scott to talk through the status of the datapacks for all OUs and get his recommendation on next steps. 

This is incredibly overdue and is really important for the panorama redesign process as a lot of the calculations in the analytics rely on the agreed upon PLHIV values disaggregated by age/sex at the SNU level.

**Comment by oharasl** [comment]
Hi all,

While this has been talked about, it is not yet on the radar for the PRIME Systems teams, especially for downstream systems' requirements. Could someone please start a Zendesk ticket or send an email to start the request?

Just a reminder that ICPI is a public repo, and we need this to become an official request to PRIME systems.

Thank you!!

Stephanie O'Hara
CTC, Inc.

**Comment by jaliasd** [comment]
We've done this, can discuss on the daq call today.

**Comment by jb3436** [comment]
Global Ticket #1719 covers the request and requirements. 

I just learned that the project that Scott is leading is called the "DataMart" project, which will be the process to get the PLHIV estimates into the PDH from DATIM. @jaliasd , would you feel comfortable reaching out to Scott to see status updates?

**Comment by oharasl** [comment]
FY2020 PLHIV data is already in PDH, so the global ticket is complete in my mind.

I am just confused by what all needs to be included as output to satisfy this request. If we shape it a little for the downstream systems team, it should be easy to fulfill. Unfortunately the requirement hadn't yet reached us. Let's talk just before/after/during the DAQ meeting

**Comment by jb3436** [comment]
Cool! Then we can figure out how to access it in PAWS and the MSD.

**Comment by jb3436** [comment]
Status
--

- **ACTION**: Review Nat-SubNat Report to see if the structure is okay or if it needs to be updated
- **STATUS**: Currently data are almost ready. They are in PDH, but a few data issues need to be resolved before it is "approved" for use. 
- **TIMELINE**: Likely to be released at FY19Q3. Could be available earlier for FY19Q2 Clean Fast Follow


Step 1 is data are available
Step 2 is Denominators projects (@jaliasd )

**Comment by jb3436** [comment]
Available
