### ISSUE TITLE
Check Global Data Cleaning Favorites

### ISSUE THREAD

**Issue by jb3436** [ICPI/DAQ#76]
Check Global Data Cleaning Favorites 
--
Request from Data Management Call: DAQ to participate in the review of the data cleaning favorites to be released
Due: Monday 7/1
Finalized 7/3
Email Subject: COP19 DATIM target cleaning favorites

### DATIM Global Cleaning Favorite Name
*See attachment for assignmetns.  [Copy of COP19 Target Cleaning DATIM Favorites v2_Assignments.xlsx](https://github.com/ICPI/DAQ/files/3346817/Copy.of.COP19.Target.Cleaning.DATIM.Favorites.v2_Assignments.xlsx)

Yellow = Shazad
Blue = Mala
Green = Jasmine 

![image](https://user-images.githubusercontent.com/13006198/60456846-6209ed80-9c08-11e9-92d8-4b669ddd5213.png)

**Comment by shazadahmed10** [comment]
Checked all of the ones assigned to me(HTS)...the correct data elements are pulled in - these are good to go.

**Comment by vanamala-narasimhan** [comment]
Check all blue favorites - correct data elements assigned

**Comment by jb3436** [comment]
Methods
--
Checked cleaning favorites in list from Couper [against 2020 target data entry screens](https://datim.zendesk.com/hc/en-us/articles/360001143166-DATIM-Data-Entry-Form-Screen-Shot-Repository) and [datapack guidance](https://www.pepfar.net/OGAC-HQ/pr/cop/SitePages/Home.aspx)

All elements match. Two inconsistencies noted in naming convention of a few disaggregates. 
![image](https://user-images.githubusercontent.com/13006198/60600320-eaf66580-9d7d-11e9-8c96-e326d5e15dcb.png)

**Comment by jb3436** [comment]
Roha cleared the cleaning favorites to be pushed to prod with the naming updates suggested

**Comment by jb3436** [comment]
Send the below links in response to a request by Tim who wanted to ensure that he got the correct favorites. 

Name | UID | Link
-- | -- | --
PEPFAR FY20 Targets PMTCT_STAT (Denominator) D Age/Sex Completeness   Review Pivot | JclrTijEjUm | https://pilot-analytics.datim.org/dhis-web-pivot/index.html?id=JclrTijEjUm
PEPFAR FY20 Targets PMTCT_STAT (Numerator) N   Age/Sex/KnownNewResult Completeness Review Pivot | iwFYIv3K22v | https://pilot-analytics.datim.org/dhis-web-pivot/index.html?id=iwFYIv3K22v
