### ISSUE TITLE
DRT Webinar

### ISSUE THREAD

**Issue by kschlenker** [ICPI/DAQ#9]
Update training materials & hold webinar for HQ & Field staff to train users on how to use the DRT Genie Extracts. Coordinate w/ Kristin Roha & Coordination Cluster.

Anyone else interested in assisting with this?

**Comment by kschlenker** [comment]
@shazadahmed10 I posted an [anonymized DRT](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/Data%20Access%20and%20Quality%20(DAQ)/Data%20Review%20Tool%20(DRT)/Working%20documents/DHIS2_DRT_4.12.2018%20-%20anonymized%20for%20training.xlsx) that we can use for screenshots when updating DRT training materials.

Discussed the training at DAQ leads yesterday with Roha - she said that an OGAC co-branded shallow dive webinar would have to be delayed until much later in May. Roha, Abe and I agreed it would be better to move forward by creating/posting an updated DRT slide deck & pre-recording a video going over the tool ASAP. Though we can still include a short DRT piece in the shallow dive webinar & link to our already created training materials.

**Comment by shazadahmed10** [comment]
Shazad's slides posted here:

[DRT Training for Genie_SA edits.pptx](https://github.com/ICPI/DAQ/files/1952192/DRT.Training.for.Genie_SA.edits.pptx)

**Comment by kschlenker** [comment]
Training powerpoint posted on sharepoint here: [https://www.pepfar.net/OGAC-HQ/icpi/Products/Webinars/2018/Data%20Review%20Tool%20(DRT)/DRT%20Training%20for%20Genie.pptx](https://www.pepfar.net/OGAC-HQ/icpi/Products/Webinars/2018/Data%20Review%20Tool%20(DRT)/DRT%20Training%20for%20Genie.pptx)

@shazadahmed10 @abrahamagedewICPI please let me know if you have suggestions/edits.

**Comment by kkale25** [comment]
is this the final version of the training PPT?

**Comment by abrahamagedewICPI** [comment]
@kkale25, yes this is the final version.
